### ISSUE TITLE
Nx_TCP_Echo_Client on Nucleo-H743ZI2: ETH not working

### ISSUE THREAD

**Issue by ekdDev** [STMicroelectronics/x-cube-azrtos-h7#12]
Hi there,

i am trying to get into Microsoft Azure RTOS IoT Development and i loaded via STM32CubeIDE the NX_TCP_Echo_Client Example for Nucleo-H723ZG which is for my understanding pin compatible.

I can build the project and deploy it to the target.

But i dont see any DHCP packets in Wireshark.

When i run the LwIP_HTTP_SERVER_Netconn_RTOS Example everything is working fine. So my managed switch / wireshark setup is ok.

Can you give me a hint?

**Comment by ALABSTM** [comment]
Hi @ekdDev,

Thank you for your interest into our products and solutions. Actually, this support channel is exclusively dedicated to report bugs or propose fixes and enhancements to the software published inside this repository.

For any other support request like yours, please submit your report to the **ST Community** [here](https://community.st.com/s/topic/0TO3W0000004ZG8WAM/azurertos).

Please allow me to close this issue. Thank you for your comprehension.

With regards,
