### ISSUE TITLE
How to use Threadx

### ISSUE THREAD

**Issue by zsjlovestudy** [STMicroelectronics/x-cube-azrtos-h7#20]
Environment:
STM32CubeIDE 1.8.0
STM32CubeMX 6.4.0
x-cube-azrtos-h7 2.0.0

I only initialized the RCC clock and an LED IO port，then i choose threadx core in software pack of x-cube-azrtos-h7.
After I added an LED flashing thread, but it didn't run
![image](https://user-images.githubusercontent.com/52393677/151303129-9a07919a-868a-4abf-9f5d-e92835a09a53.png)

**Comment by c4chris** [comment]
You need to allocate memory before calling tx_thread_create, e.g.

```
CHAR *pointer;

ret = tx_byte_allocate(byte_pool, (VOID **) &pointer, DEFAULT_STACK_SIZE, TX_NO_WAIT);

ret = tx_thread_create(&my_thread, "My Thread", my_thread_entry, 0, pointer, DEFAULT_STACK_SIZE, DEFAULT_THREAD_PRIO,
                  DEFAULT_PREEMPTION_THRESHOLD, TX_NO_TIME_SLICE, TX_AUTO_START);
```

You might want to check the value of `ret` after each call

**Comment by zsjlovestudy** [comment]
> CHAR *pointer;
> 
> ret = tx_byte_allocate(byte_pool, (VOID **) &pointer, DEFAULT_STACK_SIZE, TX_NO_WAIT);

thank you very much！ I was careless and tried Azure for the first time.

**Comment by zsjlovestudy** [comment]
> You need to allocate memory before calling tx_thread_create, e.g.
> 
> ```
> CHAR *pointer;
> 
> ret = tx_byte_allocate(byte_pool, (VOID **) &pointer, DEFAULT_STACK_SIZE, TX_NO_WAIT);
> 
> ret = tx_thread_create(&my_thread, "My Thread", my_thread_entry, 0, pointer, DEFAULT_STACK_SIZE, DEFAULT_THREAD_PRIO,
>                   DEFAULT_PREEMPTION_THRESHOLD, TX_NO_TIME_SLICE, TX_AUTO_START);
> ```
> 
> You might want to check the value of `ret` after each call

May I ask you another question, if I choose dynamic memory allocation, how should I allocate for it?  

![image](https://user-images.githubusercontent.com/52393677/151535266-119e3361-7a5e-4a32-afc3-ecce61bd269a.png)
![image](https://user-images.githubusercontent.com/52393677/151535283-ca553d0b-55c9-4289-bf59-2c39b6842cdf.png)

**Comment by ALABSTM** [comment]
Hi @zsjlovestudy,

Your questions are more than welcome. However, the right channel to ask for support about such aspects is the **ST Community** via a post on the **Azure RTOS** dedicated [section](https://community.st.com/s/topic/0TO3W0000004ZG8WAM/azurertos).

This channel is rather dedicated to report bugs or enhancements related to the firmware published within this repo.

Please allow me to close this issue. Thank you for your comprehension.

With regards,
