### ISSUE TITLE
usb dma

### ISSUE THREAD

**Issue by chengshuihang** [STMicroelectronics/x-cube-azrtos-h7#26]
您好！我想启用USB的DMA功能，我看到USBX中使用_ux_utility_memory_allocate来保证内存对齐，如果我需要启用cache，是不是只需要在HAL_HCD_HC_SubmitRequest前后调用SCB_CleanDCache_by_Addr或者SCB_InvalidateDCache_by_Addr函数即可？如下面截图这样的修改。
![image](https://user-images.githubusercontent.com/45716763/175798689-be6309ef-8872-418c-9fe8-f60f0c8b7d41.png)
![image](https://user-images.githubusercontent.com/45716763/175798713-ef1004d6-3321-4a33-8e5a-4dcb9fc6c399.png)
![image](https://user-images.githubusercontent.com/45716763/175798719-bb5e5f75-a8cd-41f9-983d-e4621977fc3c.png)
![image](https://user-images.githubusercontent.com/45716763/175798731-b3800ef0-4aa8-4eb0-bb3e-8fc7788db81c.png)
![image](https://user-images.githubusercontent.com/45716763/175798733-206a5a9c-d523-4e2f-84ef-1810bd83fa76.png)
![image](https://user-images.githubusercontent.com/45716763/175798740-40473348-6473-4c13-80d2-e18918696c72.png)
![image](https://user-images.githubusercontent.com/45716763/175798743-01502517-84cd-48f5-898b-d5af272ecb9d.png)

**Comment by ALABSTM** [comment]
Hi @chengshuihang,

Would you mind resubmitting this issue in English please? In the meanwhile, please allow me to close this one as written in Chinese.

With regards,

**Comment by chengshuihang** [comment]
您关闭它吧，我不介意。另外我英文水平可能不够，就不再用英文提交了&nbsp;


流利偷。。。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ali ***@***.***&gt;; 
发送时间: 2022年7月27日(星期三) 晚上7:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [STMicroelectronics/x-cube-azrtos-h7] usb dma (Issue #26)





 
Hi @chengshuihang,
 
Would you mind resubmitting this issue in English please? In the meanwhile, please allow me to close this one as written in Chinese.
 
With regards,
